import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// The site is hosted at https://mansadiallo.github.io/EcoVigil/ (a subdirectory, not the root directory).
// "base" must exactly match the name of the GitHub repository, otherwise the files
// JS/CSS generated by the build will be looked for in the wrong place and the page will remain blank.
export default defineConfig({
  plugins: [react()],
  base: "/EcoVigil/",
  build: {
    outDir: "dist",
  },
});
